version: '2'
services:
  db:
    image: postgres:9.5
  web:
    build: .
    command: mix phoenix.server
    volumes:
      - .:/YOUR_APP_FOLDER_NAME
    ports:
      - "4000:4000"
    depends_on:
      - db
